# This is a basic workflow to help you get started with Actions

name: Unit Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-unit-test:
    name: Unit tests on Windows MSVC
    runs-on: windows-latest
    strategy:
      matrix:
        float-precision: [2]
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: make build directory
        shell: cmd
        run: mkdir build_dir

      - name: cmake configure
        shell: cmd
        run: cmake ..
        working-directory: build_dir

      - name: cmake build
        run: cmake --build .
        working-directory: build_dir

      - name: run test
        run: ./build_dir/Debug/test.exe
        # working-directory:
  macos-unit-test:
    name: Unit tests on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        float-precision: [2]
    steps:
      - uses: actions/checkout@v2

      - name: cmake configure
        run: cmake .
      - name: cmake build
        run: cmake --build .
      - name: run test
        run: ./test
  linux-unit-test:
    name: Unit tests on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        float-precision: [2]
    steps:
      - uses: actions/checkout@v2

      - name: cmake configure
        run: cmake .
      - name: cmake build
        run: cmake --build .
      - name: run test
        run: ./test
