# This is a basic workflow to help you get started with Actions

name: Unit Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-unit-test:
    name: Unit tests on Windows MSVC
    runs-on: windows-latest
    strategy:
      matrix:
        float-precision: [2]
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: make build directory
        shell: cmd
        run: mkdir build
      - name: cmake configure
        shell: cmd
        run: |
          cd build
          cmake ..
      - name: cmake build
        run: |
          cd build
          cmake --build .
      - name: run test
        run: |
          cd build
          ctest
  macos-unit-test:
    name: Unit tests on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        float-precision: [2]
    steps:
      - uses: actions/checkout@v2

      - name: create build directory
        run: mkdir build
      - name: cmake configure
        run: |
          cd build
          cmake ..
      - name: cmake build
        run: |
          cd build
          cmake --build .
      - name: run test
        run: |
          cd build
          ctest
  linux-unit-test:
    name: Unit tests on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        float-precision: [2]
    steps:
      - uses: actions/checkout@v2

      - name: create build directory
        run: mkdir build
      - name: cmake configure
        run: |
          cd build
          cmake ..
      - name: cmake build
        run: |
          cd build
          cmake --build .
      - name: run test
        run: |
          cd build
          ctest